server:
  port: 9090
  servlet:
    context-path: /
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      use_sql_comments: true
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        hbm2ddl:
          auto: none  # entity에 설정한 조인 관계에 대한 제약조건(외래키 등)을 hibernate에서 자동으로 생성하지 않게 하는 코드
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type: TRACE

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: C##WEBMONSTER
    password: WEBMONSTER

# sms api
naver-cloud-sms:
  accessKey: xZyI5jAHb2m9zxAO897V
  secretKey: gmkl7dShqdeqRXNUnzt5tM88bjqDflCWsVFqcS62
  serviceId: ncp:sms:kr:308639486747:unimanage
  senderPhone: 01062316109


org:
  hdcd:
    upload-path: C:/upload
    secret-key: n2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C*F-J@NcRf