-- 계정생성
CREATE USER C##WEBMONSTER
    IDENTIFIED BY WEBMONSTER;

-- 접속 권한
GRANT CONNECT, RESOURCE TO C##WEBMONSTER;

-- 테이블, 시퀀스 생성 권한
GRANT CREATE TABLE TO C##WEBMONSTER;
GRANT CREATE SEQUENCE TO C##WEBMONSTER;

-- 테이블 스페이스 사용 권한
ALTER USER C##WEBMONSTER QUOTA 10M ON USERS;