DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE FREEBOARD CASCADE CONSTRAINTS;
DROP TABLE FREEBOARD_REP CASCADE CONSTRAINTS;
DROP TABLE SCHEDULE CASCADE CONSTRAINTS;
DROP TABLE SCHOLARSHIP CASCADE CONSTRAINTS;
DROP TABLE TOTAL_SCORE CASCADE CONSTRAINTS;
DROP TABLE COURSE_REGI CASCADE CONSTRAINTS;
DROP TABLE GRADE CASCADE CONSTRAINTS;
DROP TABLE SCORE CASCADE CONSTRAINTS;
DROP TABLE LECTURE CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE STATUS CASCADE CONSTRAINTS;
DROP TABLE EVALUATION CASCADE CONSTRAINTS;
DROP TABLE TUITION CASCADE CONSTRAINTS;


CREATE TABLE MEMBER (
  MEMBER_ID NUMBER PRIMARY KEY,
  MEMBER_PWD VARCHAR2(100) NOT NULL,
  NAME VARCHAR2(30) NOT NULL,
  DEPARTMENT VARCHAR2(50),
  GRADE NUMBER,
  BIRTHDAY DATE NOT NULL,
  PHONE VARCHAR2(50) NOT NULL,
  EMAIL VARCHAR2(100) NOT NULL,
  POSTCODE NUMBER NOT NULL,
  ADDRESS1 VARCHAR2(100) NOT NULL,
  ADDRESS2 VARCHAR2(100) NOT NULL,
  AUTH NUMBER NOT NULL
);

COMMENT ON TABLE MEMBER IS '멤버';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NAME IS '이름';
COMMENT ON COLUMN MEMBER.DEPARTMENT IS '학과';
COMMENT ON COLUMN MEMBER.GRADE IS '학년';
COMMENT ON COLUMN MEMBER.BIRTHDAY IS '생년월일';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.POSTCODE IS '우편번호';
COMMENT ON COLUMN MEMBER.ADDRESS1 IS '상세주소1';
COMMENT ON COLUMN MEMBER.ADDRESS2 IS '상세주소2';
COMMENT ON COLUMN MEMBER.AUTH IS '회원 구분';


CREATE TABLE LECTURE (
  LECTURE_ID NUMBER PRIMARY KEY,
  MEMBER_ID NUMBER NOT NULL,
  LECTURE_TITLE VARCHAR2(20) NOT NULL,
  DEPARTMENT VARCHAR2(20) NOT NULL,
  SEMESTER NUMBER NOT NULL,
  CREDIT NUMBER NOT NULL,
  CLASSIFICATION CHAR(1) NOT NULL,
  ROOMCODE1 VARCHAR2(10) NOT NULL,
  ROOMCODE2 VARCHAR2(10),
  ROOMCODE3 VARCHAR2(10),
  TIMECODE1 NUMBER NOT NULL,
  TIMECODE2 NUMBER,
  TIMECODE3 NUMBER,
  NUMBER_OF_STUDENT NUMBER,
  SYLLABUS_TITLE VARCHAR2(100) NOT NULL,
  SYLLABUS_RENAME VARCHAR2(100),
  LECTURE_APPLY_STATUS CHAR(1) DEFAULT '1' NOT NULL,
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE LECTURE IS '강의';
COMMENT ON COLUMN LECTURE.LECTURE_ID IS '강의번호';
COMMENT ON COLUMN LECTURE.MEMBER_ID IS '아이디';
COMMENT ON COLUMN LECTURE.LECTURE_TITLE IS '강의명';
COMMENT ON COLUMN LECTURE.DEPARTMENT IS '학과명';
COMMENT ON COLUMN LECTURE.SEMESTER IS '학기';
COMMENT ON COLUMN LECTURE.CREDIT IS '학점';
COMMENT ON COLUMN LECTURE.CLASSIFICATION IS '구분';
COMMENT ON COLUMN LECTURE.ROOMCODE1 IS '강의실코드1';
COMMENT ON COLUMN LECTURE.ROOMCODE2 IS '강의실코드2';
COMMENT ON COLUMN LECTURE.ROOMCODE3 IS '강의실코드3';
COMMENT ON COLUMN LECTURE.TIMECODE1 IS '시간코드1';
COMMENT ON COLUMN LECTURE.TIMECODE2 IS '시간코드2';
COMMENT ON COLUMN LECTURE.TIMECODE3 IS '시간코드3';
COMMENT ON COLUMN LECTURE.NUMBER_OF_STUDENT IS '정원';
COMMENT ON COLUMN LECTURE.SYLLABUS_TITLE IS '강의계획서명';
COMMENT ON COLUMN LECTURE.SYLLABUS_RENAME IS '강의계획서_리네임';
COMMENT ON COLUMN LECTURE.LECTURE_APPLY_STATUS IS '강의 승인여부';



CREATE TABLE FREEBOARD (
  FREE_ID NUMBER PRIMARY KEY,
  FREE_TITLE VARCHAR2(500) NOT NULL,
  FREE_CONTENT VARCHAR2(1000) NOT NULL,
  CREATED_DATE DATE NOT NULL,
  MEMBER_ID NUMBER NOT NULL,
  CONSTRAINT FK_FREEBOARD_MEMBER_ID FOREIGN KEY (MEMBER_ID)
  REFERENCES MEMBER (MEMBER_ID)
);

COMMENT ON TABLE FREEBOARD IS '자유게시판';
COMMENT ON COLUMN FREEBOARD.FREE_ID IS '자유게시판 번호';
COMMENT ON COLUMN FREEBOARD.FREE_TITLE IS '자유게시판 제목';
COMMENT ON COLUMN FREEBOARD.FREE_CONTENT IS '자유게시판 내용';
COMMENT ON COLUMN FREEBOARD.CREATED_DATE IS '자유게시판 작성일';
COMMENT ON COLUMN FREEBOARD.MEMBER_ID IS '자유게시판 작성자';


CREATE TABLE FREEBOARD_REP (
  FREE_REP_ID NUMBER PRIMARY KEY,
  FREE_ID NUMBER NOT NULL,
  FREE_REP_CONTENT VARCHAR2(1000) NOT NULL,
  CREATED_DATE DATE NOT NULL,
  MEMBER_ID NUMBER NOT NULL,
  CONSTRAINT FK_FREEBOARD_REP_FREE_ID FOREIGN KEY (FREE_ID)
  REFERENCES FREEBOARD (FREE_ID),
  CONSTRAINT FK_FREEBOARD_REP_MEMBER_ID FOREIGN KEY (MEMBER_ID)
  REFERENCES MEMBER (MEMBER_ID)
);

COMMENT ON TABLE FREEBOARD_REP IS '자유게시판 댓글';
COMMENT ON COLUMN FREEBOARD_REP.FREE_REP_ID IS '자유게시판 댓글 번호';
COMMENT ON COLUMN FREEBOARD_REP.FREE_ID IS '자유게시판 번호';
COMMENT ON COLUMN FREEBOARD_REP.FREE_REP_CONTENT IS '댓글 내용';
COMMENT ON COLUMN FREEBOARD_REP.CREATED_DATE IS '댓글 작성일';
COMMENT ON COLUMN FREEBOARD_REP.MEMBER_ID IS '댓글 작성자';


CREATE TABLE SCHEDULE (
  SCHE_ID NUMBER PRIMARY KEY,
  SCHE_TITLE VARCHAR2(500) NOT NULL,
  SCHE_CONTENT VARCHAR2(1000),
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL
);


COMMENT ON TABLE SCHEDULE IS '학사일정';
COMMENT ON COLUMN SCHEDULE.SCHE_ID IS '학사일정 번호';
COMMENT ON COLUMN SCHEDULE.SCHE_TITLE IS '학사일정 제목';
COMMENT ON COLUMN SCHEDULE.SCHE_CONTENT IS '학사일정 내용';
COMMENT ON COLUMN SCHEDULE.START_DATE IS '학사일정 시작날짜';
COMMENT ON COLUMN SCHEDULE.END_DATE IS '학사일정 끝날짜';


CREATE TABLE STATUS (
  STATUS_ID NUMBER PRIMARY KEY,
  MEMBER_ID NUMBER NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  REASON_OF_LEAVE VARCHAR2(100),
  RETURN_DATE DATE NOT NULL,
  APPLY_LEAVE_DATE DATE DEFAULT SYSDATE,
  APPLY_RETURN_DATE DATE DEFAULT SYSDATE,
  ALLOWED_LEAVE CHAR(1)  DEFAULT '1' NOT NULL,
  CONSTRAINT FK_STATUS_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

COMMENT ON TABLE STATUS IS '학적변동';
COMMENT ON COLUMN STATUS.STATUS_ID IS '학적변동 번호';
COMMENT ON COLUMN STATUS.MEMBER_ID IS '멤버 번호';
COMMENT ON COLUMN STATUS.START_DATE IS '휴학 시작일';
COMMENT ON COLUMN STATUS.END_DATE IS '휴학 끝일';
COMMENT ON COLUMN STATUS.REASON_OF_LEAVE IS '휴학사유';
COMMENT ON COLUMN STATUS.RETURN_DATE IS '복학일';
COMMENT ON COLUMN STATUS.APPLY_LEAVE_DATE IS '휴학접수날짜';
COMMENT ON COLUMN STATUS.APPLY_RETURN_DATE IS '복학접수날짜';
COMMENT ON COLUMN STATUS.ALLOWED_LEAVE IS '휴/복학허용여부';



CREATE TABLE SCHOLARSHIP (
  SCHO_ID NUMBER PRIMARY KEY,
  SCHO_TERM NUMBER,
  SCHO_NAME VARCHAR2(100),
  AMOUNT NUMBER NOT NULL,
  MEMBER_ID NUMBER,
  CONSTRAINT FK_SCHOLARSHIP_MEMBER_ID FOREIGN KEY (MEMBER_ID)
  REFERENCES MEMBER (MEMBER_ID)
);

COMMENT ON TABLE SCHOLARSHIP IS '장학금';
COMMENT ON COLUMN SCHOLARSHIP.SCHO_ID IS '장학금 번호';
COMMENT ON COLUMN SCHOLARSHIP.SCHO_TERM IS '장학금 학기';
COMMENT ON COLUMN SCHOLARSHIP.SCHO_NAME IS '장학금명';
COMMENT ON COLUMN SCHOLARSHIP.AMOUNT IS '장학금액';
COMMENT ON COLUMN SCHOLARSHIP.MEMBER_ID IS '멤버 번호';



CREATE TABLE COURSE_REGI (
  COURSE_REGI_ID NUMBER PRIMARY KEY,
  MEMBER_ID NUMBER NOT NULL,
  LECTURE_ID NUMBER NOT NULL,
  COURSE_REGI_TERM NUMBER NOT NULL,
  CONSTRAINT FK_COURSE_REGI_MEMBER_ID FOREIGN KEY (MEMBER_ID)
  REFERENCES MEMBER (MEMBER_ID),
  CONSTRAINT FK_COURSE_REGI_LECTURE_ID FOREIGN KEY (LECTURE_ID)
  REFERENCES LECTURE (LECTURE_ID)
);

COMMENT ON TABLE COURSE_REGI IS '수강신청';
COMMENT ON COLUMN COURSE_REGI.COURSE_REGI_ID IS '수강신청 번호';
COMMENT ON COLUMN COURSE_REGI.MEMBER_ID IS '멤버 번호';
COMMENT ON COLUMN COURSE_REGI.LECTURE_ID IS '강의 ID';
COMMENT ON COLUMN COURSE_REGI.COURSE_REGI_TERM IS '신청학기';


CREATE TABLE TUITION (
  TUITION_ID NUMBER PRIMARY KEY,
  MEMBER_ID NUMBER NOT NULL,
  TUITION_AMOUNT NUMBER NOT NULL,
  PAID CHAR(1) DEFAULT 'N' NOT NULL,
  TUITION_TERM NUMBER NOT NULL
);

COMMENT ON TABLE TUITION IS '등록금';
COMMENT ON COLUMN TUITION. TUITION_ID IS '등록금 번호';
COMMENT ON COLUMN TUITION.MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN TUITION.TUITION_AMOUNT IS '등록금액';
COMMENT ON COLUMN TUITION.PAID IS '납부여부';
COMMENT ON COLUMN TUITION.TUITION_TERM IS '등록금 학기';

CREATE TABLE SCORE (
  SCORE_ID NUMBER PRIMARY KEY,
  MEMBER_ID NUMBER NOT NULL,
  LECTURE_ID NUMBER NOT NULL,
  MID_SCORE NUMBER NOT NULL,
  FINAL_SCORE NUMBER NOT NULL,
  ASSIGN_SCORE NUMBER NOT NULL,
  TOTAL_SCORE NUMBER NOT NULL,
  CONSTRAINT FK_GRADE_MEMBER_ID FOREIGN KEY (MEMBER_ID)
  REFERENCES MEMBER (MEMBER_ID),
  CONSTRAINT FK_GRADE_LECTURE_ID FOREIGN KEY (LECTURE_ID) REFERENCES LECTURE (LECTURE_ID)
);

COMMENT ON TABLE SCORE IS '성적';
COMMENT ON COLUMN SCORE.SCORE_ID IS '성적 번호';
COMMENT ON COLUMN SCORE.MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN SCORE.LECTURE_ID IS '강의 ID';
COMMENT ON COLUMN SCORE.MID_SCORE IS '중간고사 점수';
COMMENT ON COLUMN SCORE.FINAL_SCORE IS '기말고사 점수';
COMMENT ON COLUMN SCORE.ASSIGN_SCORE IS '과제점수';
COMMENT ON COLUMN SCORE.TOTAL_SCORE IS '학기 총점수';


CREATE TABLE TOTAL_SCORE (
MEMBER_ID NUMBER NOT NULL,
TOTAL_AVERAGE NUMBER NOT NULL,
MAX_CREDIT NUMBER NOT NULL,
NOW_CREDIT NUMBER NOT NULL,
CONSTRAINT FK_TOTAL_SCORE_MEMBER_ID FOREIGN KEY (MEMBER_ID)
REFERENCES MEMBER (MEMBER_ID)
);

COMMENT ON TABLE TOTAL_SCORE IS '총학기 성적';
COMMENT ON COLUMN  TOTAL_SCORE .MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN TOTAL_SCORE .TOTAL_AVERAGE IS '전체학기 평점';
COMMENT ON COLUMN TOTAL_SCORE .MAX_CREDIT IS '최대 이수학점';
COMMENT ON COLUMN TOTAL_SCORE .NOW_CREDIT IS '현재 이수학점';


CREATE TABLE EVALUATION (
  EVALUATION_ID NUMBER PRIMARY KEY,
  MEMBER_ID NUMBER NOT NULL,
  LECTURE_ID NUMBER NOT NULL,
  SCORE1 NUMBER NOT NULL,
  SCORE2 NUMBER NOT NULL,
  SCORE3 NUMBER NOT NULL,
  SCORE4 NUMBER NOT NULL,
  SCORE5 NUMBER NOT NULL,
  COMMENTS VARCHAR2(300),
  CONSTRAINT FK_EVALUATION_MEMBER_ID FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER (MEMBER_ID),
  CONSTRAINT FK_EVALUATION_LECTURE_ID FOREIGN KEY (LECTURE_ID)
    REFERENCES LECTURE (LECTURE_ID)
);

COMMENT ON TABLE EVALUATION IS '강의평가';
COMMENT ON COLUMN EVALUATION.EVALUATION_ID IS '강의평가 번호';
COMMENT ON COLUMN EVALUATION.MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN EVALUATION.LECTURE_ID IS '강의 ID';
COMMENT ON COLUMN EVALUATION.SCORE1 IS '1번 문항 점수';
COMMENT ON COLUMN EVALUATION.SCORE2 IS '2번 문항 점수';
COMMENT ON COLUMN EVALUATION.SCORE3 IS '3번 문항 점수';
COMMENT ON COLUMN EVALUATION.SCORE4 IS '4번 문항 점수';
COMMENT ON COLUMN EVALUATION.SCORE5 IS '5번 문항 점수';
COMMENT ON COLUMN EVALUATION.COMMENTS IS '하고싶은 말';



CREATE TABLE NOTICE (
  NOTICE_ID NUMBER PRIMARY KEY,
  NOTICE_TITLE VARCHAR2(500) NOT NULL,
  NOTICE_CONTENT VARCHAR2(1000),
  MEMBER_ID NUMBER,
  CREATED_DATE DATE,
  READCOUNT NUMBER DEFAULT '0',
  CONSTRAINT FK_NOTICE_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

COMMENT ON TABLE  NOTICE IS '전체 공지사항';
COMMENT ON COLUMN  NOTICE.NOTICE_ID IS '공지사항 번호';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지사항 제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '공지사항 내용';
COMMENT ON COLUMN NOTICE.MEMBER_ID IS '작성자';
COMMENT ON COLUMN NOTICE.CREATED_DATE IS '등록일';
COMMENT ON COLUMN NOTICE.READCOUNT IS '조회수';


CREATE SEQUENCE LECTURE_ID_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE FREE_ID_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE FREE_REP_ID_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE SCHE_ID_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE STATUS_ID_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE SCHO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE COURSE_REGI_ID_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE TUITION_ID_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE SCORE_ID_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE EVALUATION_ID_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE NOTICE_ID_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE;


commit;

